services:
  console.devel_dumper:
    class: Drupal\Console\Command\DevelDumperCommand
    arguments: ['@?plugin.manager.devel_dumper']
    tags:
      - { name: drupal.command }
    lazy: true
  console.shell:
    class: Drupal\Console\Command\ShellCommand
    tags:
      - { name: drupal.command }
    lazy: true
